[project]
src = "src"

[networks.contracts.price_feed]
deployer_script = "script/deploy_mocks.py"

[networks.sepolia]
url = "$SEPOLIA_RPC_URL"
save_to_db = true
default_account_name = "default"
explorer_uri = "https://eth-sepolia.blockscout.com/"
explorer_type = "blockscout"

[networks.pyevm.contracts.price_feed]

[networks.sepolia.contracts.price_feed]
address = "0x694AA1769357215DE4FAC081bf1f309aDC325306"
